WITH CTE AS
(
    SELECT 
    STARTED_AT
    FROM {{ source('demo', 'bike') }}
    WHERE STARTED_AT<>'stoptime'
)
SELECT 
TO_TIMESTAMP(STARTED_AT) STARTED_AT,
TO_DATE(STARTED_AT) STARTED_AT_DT,
DAYNAME(STARTED_AT_DT) DAYNAME,
DAYOFWEEK(STARTED_AT_DT) DAYOFWEEK,
{{get_season('STARTED_AT_DT')}} SEASON,

{{case_stmt1('DAYNAME')}} "Weekdays?"

 FROM CTE